server:
  port: 9000

spring:
  application:
    name: dev-environment
  config:
    import: configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: "*"