version: '3.8'

services:

  zookeeper-01:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper-dr-01
    networks:
      - docker-local-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-01:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka-dr-01
    depends_on:
      - zookeeper-01
    ports:
      - 9092:9092
    networks:
      - docker-local-network      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   

  kafdrop-01:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop-dr-01
    networks: 
      - docker-local-network
    depends_on:
      - kafka-01
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-01:29092


networks: 
  docker-local-network:
    driver: bridge  