// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/mserpa/protobuf/client/proto/book.proto

package com.mserpa.protobuf.client.compiledproto;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageCardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string user = 1;
    /**
     * <code>required string user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>required string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>required string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    // required string text = 2;
    /**
     * <code>required string text = 2;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code com.mserpa.protobuf.client.compiledproto.MessageCard}
   */
  public static final class MessageCard extends
      com.google.protobuf.GeneratedMessage
      implements MessageCardOrBuilder {
    // Use MessageCard.newBuilder() to construct.
    private MessageCard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageCard(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageCard defaultInstance;
    public static MessageCard getDefaultInstance() {
      return defaultInstance;
    }

    public MessageCard getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              user_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.class, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageCard> PARSER =
        new com.google.protobuf.AbstractParser<MessageCard>() {
      public MessageCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageCard(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageCard> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.lang.Object user_;
    /**
     * <code>required string user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private java.lang.Object text_;
    /**
     * <code>required string text = 2;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      user_ = "";
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mserpa.protobuf.client.compiledproto.Protos.MessageCard prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mserpa.protobuf.client.compiledproto.MessageCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.class, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder.class);
      }

      // Construct using com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor;
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard getDefaultInstanceForType() {
        return com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.getDefaultInstance();
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard build() {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard buildPartial() {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageCard result = new com.mserpa.protobuf.client.compiledproto.Protos.MessageCard(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mserpa.protobuf.client.compiledproto.Protos.MessageCard) {
          return mergeFrom((com.mserpa.protobuf.client.compiledproto.Protos.MessageCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mserpa.protobuf.client.compiledproto.Protos.MessageCard other) {
        if (other == com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.getDefaultInstance()) return this;
        if (other.hasUser()) {
          bitField0_ |= 0x00000001;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000002;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUser()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mserpa.protobuf.client.compiledproto.Protos.MessageCard) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string user = 1;
      private java.lang.Object user_ = "";
      /**
       * <code>required string user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }

      // required string text = 2;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 2;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mserpa.protobuf.client.compiledproto.MessageCard)
    }

    static {
      defaultInstance = new MessageCard(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mserpa.protobuf.client.compiledproto.MessageCard)
  }

  public interface MessageListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> 
        getMessagesList();
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    com.mserpa.protobuf.client.compiledproto.Protos.MessageCard getMessages(int index);
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    java.util.List<? extends com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mserpa.protobuf.client.compiledproto.MessageList}
   */
  public static final class MessageList extends
      com.google.protobuf.GeneratedMessage
      implements MessageListOrBuilder {
    // Use MessageList.newBuilder() to construct.
    private MessageList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageList defaultInstance;
    public static MessageList getDefaultInstance() {
      return defaultInstance;
    }

    public MessageList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messages_ = new java.util.ArrayList<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(input.readMessage(com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mserpa.protobuf.client.compiledproto.Protos.MessageList.class, com.mserpa.protobuf.client.compiledproto.Protos.MessageList.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageList> PARSER =
        new com.google.protobuf.AbstractParser<MessageList>() {
      public MessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageList> getParserForType() {
      return PARSER;
    }

    // repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;
    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> messages_;
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    public java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    public java.util.List<? extends com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
     */
    public com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private void initFields() {
      messages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMessagesCount(); i++) {
        if (!getMessages(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mserpa.protobuf.client.compiledproto.Protos.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mserpa.protobuf.client.compiledproto.Protos.MessageList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mserpa.protobuf.client.compiledproto.MessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mserpa.protobuf.client.compiledproto.Protos.MessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mserpa.protobuf.client.compiledproto.Protos.MessageList.class, com.mserpa.protobuf.client.compiledproto.Protos.MessageList.Builder.class);
      }

      // Construct using com.mserpa.protobuf.client.compiledproto.Protos.MessageList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mserpa.protobuf.client.compiledproto.Protos.internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor;
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageList getDefaultInstanceForType() {
        return com.mserpa.protobuf.client.compiledproto.Protos.MessageList.getDefaultInstance();
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageList build() {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mserpa.protobuf.client.compiledproto.Protos.MessageList buildPartial() {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageList result = new com.mserpa.protobuf.client.compiledproto.Protos.MessageList(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mserpa.protobuf.client.compiledproto.Protos.MessageList) {
          return mergeFrom((com.mserpa.protobuf.client.compiledproto.Protos.MessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mserpa.protobuf.client.compiledproto.Protos.MessageList other) {
        if (other == com.mserpa.protobuf.client.compiledproto.Protos.MessageList.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMessagesCount(); i++) {
          if (!getMessages(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mserpa.protobuf.client.compiledproto.Protos.MessageList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mserpa.protobuf.client.compiledproto.Protos.MessageList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;
      private java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new java.util.ArrayList<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mserpa.protobuf.client.compiledproto.Protos.MessageCard, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder, com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder addMessages(com.mserpa.protobuf.client.compiledproto.Protos.MessageCard value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder addMessages(
          com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.mserpa.protobuf.client.compiledproto.Protos.MessageCard> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          super.addAll(values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public java.util.List<? extends com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mserpa.protobuf.client.compiledproto.MessageCard messages = 1;</code>
       */
      public java.util.List<com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mserpa.protobuf.client.compiledproto.Protos.MessageCard, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder, com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mserpa.protobuf.client.compiledproto.Protos.MessageCard, com.mserpa.protobuf.client.compiledproto.Protos.MessageCard.Builder, com.mserpa.protobuf.client.compiledproto.Protos.MessageCardOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.mserpa.protobuf.client.compiledproto.MessageList)
    }

    static {
      defaultInstance = new MessageList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mserpa.protobuf.client.compiledproto.MessageList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9src/main/java/com/mserpa/protobuf/clie" +
      "nt/proto/book.proto\022(com.mserpa.protobuf" +
      ".client.compiledproto\")\n\013MessageCard\022\014\n\004" +
      "user\030\001 \002(\t\022\014\n\004text\030\002 \002(\t\"V\n\013MessageList\022" +
      "G\n\010messages\030\001 \003(\01325.com.mserpa.protobuf." +
      "client.compiledproto.MessageCardB2\n(com." +
      "mserpa.protobuf.client.compiledprotoB\006Pr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mserpa_protobuf_client_compiledproto_MessageCard_descriptor,
              new java.lang.String[] { "User", "Text", });
          internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mserpa_protobuf_client_compiledproto_MessageList_descriptor,
              new java.lang.String[] { "Messages", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
