version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: marceloserpa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mypoc
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5442:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

volumes:
  init.sh: